# Generated by Django 2.1.1 on 2018-10-10 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20181009_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='popular',
            field=models.IntegerField(default=0, verbose_name='人气指数'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 9, 29, 39, 891177), verbose_name='创建时间'),
        ),
    ]
