# Generated by Django 2.1.1 on 2018-09-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='电子邮箱'),
        ),
    ]
